#!/bin/bash

# Updating the project
printf "Updating the project\n\n"
git fetch && git pull

# Building the project
printf "\nBuilding the project\n\n"
docker compose build

# Starting the project
printf "\nStarting the project\n\n"
docker compose up -d
